### PR TITLE
Add enableSplunkWebSSL paramenter setup.

### PR DESCRIPTION
**Pull request by xueshanf**
Needed if run a proxy front end.

### CODE REVIEW

**Comment by xeor** [comment]
Are you sure setting it to `1` works? The docs (http://docs.splunk.com/Documentation/Splunk/latest/Admin/Webconf?r=answers#web.conf.spec) sais true|false. Also, wont you need to specify `privKeyPath` and `caCertPath` as well?

I havent looked into this because I have a reverse proxy in front that takes care of encryption, but I'm happy to add this when you confirm usage :)

**Comment by xueshanf** [comment]
@xeor  Set to 1 does work - I have been running with that setting, but I switched to "True" to match the docs. It also works.  
I use reverse proxy which also uses https to connect to  splunk web (I guess without ssl should work as well). For this settings, I used the default cert/key generated by the splunk installation.

**Comment by xeor** [comment]
Alright, cool, I see. Testing Splunk with ssl (even default certs) would be useful.
The user can set this to true, then mount in `/opt/splunk/etc/auth/splunkweb/privkey.pem` and `/opt/splunk/etc/auth/splunkweb/cert.pem` if they want the container to use another cert.

Waiting for your updated commit

**Comment by xeor** [comment]
Sorry, busy weekend. Will rebuild Docker-index later today..

**Pull request merged**
